version: "3"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shopping
    ports:
      - "5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres
  web:
    build: .
    ports:
      - "3500:3500"
    links:
      - "database:database"
    environment:
      - REACT_APP_MOMENTS_GRAPHQL_HTTP_URL=http://localhost:3500/graphql
      - REACT_APP_MOMENTS_GRAPHQL_WEBSOCKET_URL=ws://localhost:3500/graphql
      - DATABASE_URL=host=database port=5432 user=postgres password=docker dbname=shopping sslmode=disable
    depends_on:
      - database
