// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package app

type Item struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Amount   *float64 `json:"amount"`
	Unit     *string  `json:"unit"`
	Section  *string  `json:"section"`
	Checked  *bool    `json:"checked"`
	Deleted  *bool    `json:"deleted"`
	Position *int     `json:"position"`
}

type NewItem struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Amount   *float64 `json:"amount"`
	Unit     *string  `json:"unit"`
	Section  *string  `json:"section"`
	Checked  *bool    `json:"checked"`
	Deleted  *bool    `json:"deleted"`
	Position *int     `json:"position"`
	Table    string   `json:"table"`
}

type NewSection struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Position int    `json:"position"`
	Table    string `json:"table"`
}

type NewTableMap struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type Section struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Position int    `json:"position"`
}

type SubscritionInput struct {
	ID    string `json:"id"`
	Table string `json:"table"`
}

type Suggestion struct {
	Name    string `json:"name"`
	Unit    string `json:"unit"`
	Section string `json:"section"`
}

type Table struct {
	Sections []*Section `json:"sections"`
	Items    []*Item    `json:"items"`
}

type TableMap struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}
