// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package app

type DeleteItem struct {
	ID    string `json:"id"`
	Table string `json:"table"`
}

type DeleteSection struct {
	ID    string `json:"id"`
	Table string `json:"table"`
}

type Item struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Amount   *float64 `json:"amount"`
	Unit     *string  `json:"unit"`
	Section  *string  `json:"section"`
	Checked  *bool    `json:"checked"`
	Deleted  *bool    `json:"deleted"`
	Position *int     `json:"position"`
}

type List struct {
	Name     string     `json:"name"`
	ID       string     `json:"id"`
	Listtype string     `json:"listtype"`
	Owner    bool       `json:"owner"`
	Sections []*Section `json:"sections"`
	Items    []*Item    `json:"items"`
}

type NewItem struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Amount   *float64 `json:"amount"`
	Unit     *string  `json:"unit"`
	Section  *string  `json:"section"`
	Checked  *bool    `json:"checked"`
	Deleted  *bool    `json:"deleted"`
	Position *int     `json:"position"`
	Table    string   `json:"table"`
}

type NewList struct {
	Name     string `json:"name"`
	Listtype string `json:"listtype"`
	ID       string `json:"id"`
}

type NewSection struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Position int    `json:"position"`
	Table    string `json:"table"`
}

type Section struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Position int    `json:"position"`
}

type SubscritionInput struct {
	ID    string `json:"id"`
	Table string `json:"table"`
}

type Suggestion struct {
	Name    string `json:"name"`
	Unit    string `json:"unit"`
	Section string `json:"section"`
}
